openapi: 3.0.1
info:
  title: API-Python-Hospital
  description: API Definition of API-Python-Hospital
  version: 1.0.0
servers:
- url: http://localhost:8290/api-python-hospital
paths:
  /:
    get:
      responses:
        default:
          description: Default response
