# Generated by Django 3.2.25 on 2025-01-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20250121_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdisease',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdisease',
            name='fatalOutcome',
            field=models.BooleanField(default=False),
        ),
    ]
