//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.23 at 05:11:47 AM MSK 
//


package ru.hazov.javahospitalsoap.jaxb_model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.hazov.javahospitalsoap.jaxb_model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.hazov.javahospitalsoap.jaxb_model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Covid19PatientsReport }
     * 
     */
    public Covid19PatientsReport createCovid19PatientsReport() {
        return new Covid19PatientsReport();
    }

    /**
     * Create an instance of {@link Covid19Patient }
     * 
     */
    public Covid19Patient createCovid19Patient() {
        return new Covid19Patient();
    }

    /**
     * Create an instance of {@link CreateDiseaseRequest }
     * 
     */
    public CreateDiseaseRequest createCreateDiseaseRequest() {
        return new CreateDiseaseRequest();
    }

    /**
     * Create an instance of {@link CreateDiseaseResponse }
     * 
     */
    public CreateDiseaseResponse createCreateDiseaseResponse() {
        return new CreateDiseaseResponse();
    }

    /**
     * Create an instance of {@link CreatePatientRequest }
     * 
     */
    public CreatePatientRequest createCreatePatientRequest() {
        return new CreatePatientRequest();
    }

    /**
     * Create an instance of {@link CreatePatientResponse }
     * 
     */
    public CreatePatientResponse createCreatePatientResponse() {
        return new CreatePatientResponse();
    }

    /**
     * Create an instance of {@link GetPatientsRequest }
     * 
     */
    public GetPatientsRequest createGetPatientsRequest() {
        return new GetPatientsRequest();
    }

    /**
     * Create an instance of {@link GetPatientsResponse }
     * 
     */
    public GetPatientsResponse createGetPatientsResponse() {
        return new GetPatientsResponse();
    }

    /**
     * Create an instance of {@link Patient }
     * 
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link DiseaseInfo }
     * 
     */
    public DiseaseInfo createDiseaseInfo() {
        return new DiseaseInfo();
    }

    /**
     * Create an instance of {@link Medicament }
     * 
     */
    public Medicament createMedicament() {
        return new Medicament();
    }

}
