//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.23 at 05:11:47 AM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.hazov.ru/javahospitalsoap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.hazov.javahospitalsoap.jaxb_model;
